"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

interface LanguageContextType {
  language: string
  setLanguage: (lang: string) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.cars": "Cars",
    "nav.employees": "Employees",
    "nav.routeOptimization": "Route Optimization",

    // Common
    "common.loading": "Loading...",
    "common.search": "Search...",
    "common.filter": "Filter",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.add": "Add",
    "common.update": "Update",
    "common.export": "Export Excel",
    "common.import": "Import Excel",
    "common.importing": "Importing...",
    "common.exporting": "Exporting...",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.all": "All",
    "common.clear": "Clear",
    "common.previous": "Previous",
    "common.next": "Next",
    "common.page": "Page",
    "common.of": "of",
    "common.showing": "Showing",
    "common.results": "results",
    "common.for": "for",
    "common.required": "required",

    // Home Page
    "home.title": "Bus Organizer",
    "home.subtitle":
      "Transform your personnel transportation with intelligent route optimization, comprehensive fleet management, and seamless employee coordination.",
    "home.manageFleet": "🚗 Manage Fleet",
    "home.manageEmployees": "👥 Manage Employees",
    "home.optimizeRoutes": "🗺️ Optimize Routes",
    "home.howItWorks": "How It Works",
    "home.howItWorksSubtitle": "Follow these simple steps to optimize your personnel transportation system",
    "home.powerfulFeatures": "Powerful Features",
    "home.featuresSubtitle": "Everything you need to manage your transportation system",
    "home.readyToStart": "Ready to Get Started?",
    "home.startSubtitle": "Begin optimizing your personnel transportation system today",
    "home.faq": "Frequently Asked Questions",

    // Cars Page
    "cars.title": "Fleet Management",
    "cars.subtitle": "Manage your vehicle fleet with advanced filtering and Excel integration",
    "cars.addCar": "Add Car",
    "cars.editCar": "Edit Car",
    "cars.addNewCar": "Add New Car",
    "cars.model": "Model",
    "cars.plateNumber": "Plate Number",
    "cars.capacity": "Capacity",
    "cars.color": "Color",
    "cars.year": "Year",
    "cars.notes": "Notes",
    "cars.people": "people",
    "cars.selectColor": "Select color",
    "cars.modelPlaceholder": "e.g., Mercedes Sprinter",
    "cars.platePlaceholder": "e.g., ABC-123",
    "cars.capacityPlaceholder": "Number of passengers",
    "cars.notesPlaceholder": "Additional information about the vehicle",
    "cars.modelRequired": "Model is required",
    "cars.plateRequired": "Plate number is required",
    "cars.capacityRequired": "Capacity must be between 1 and 100",

    // Employees Page
    "employees.title": "Employee Management",
    "employees.subtitle": "Manage employee information with advanced search and Excel integration",
    "employees.addEmployee": "Add Employee",
    "employees.editEmployee": "Edit Employee",
    "employees.addNewEmployee": "Add New Employee",
    "employees.firstName": "First Name",
    "employees.lastName": "Last Name",
    "employees.jobTitle": "Job Title",
    "employees.email": "Email",
    "employees.phoneNumber": "Phone Number",
    "employees.homeAddress": "Home Address",
    "employees.dropOffPoint": "Drop-off Point",
    "employees.dropOffLatitude": "Drop-off Latitude",
    "employees.dropOffLongitude": "Drop-off Longitude",
    "employees.nearestPublicTransport": "Nearest Public Transport",
    "employees.personalInfo": "Personal Information",
    "employees.locationInfo": "Location Information",
    "employees.additionalInfo": "Additional Information",
    "employees.firstNamePlaceholder": "Enter first name",
    "employees.lastNamePlaceholder": "Enter last name",
    "employees.emailPlaceholder": "employee@company.com",

    // Route Optimization
    "routes.title": "Route Optimization",
    "routes.subtitle": "Optimize bus routes with advanced filtering and map visualization",
    "routes.workplaceLocation": "Workplace Location",
    "routes.workplaceAddress": "Workplace Address",
    "routes.getCurrentLocation": "Get Current Location",
    "routes.selectCars": "Select Cars",
    "routes.selectEmployees": "Select Employees",
    "routes.searchCars": "Search cars...",
    "routes.searchEmployees": "Search employees...",
    "routes.filterByLocation": "Filter by location...",
    "routes.minCapacity": "Min capacity",
    "routes.seats": "seats",
    "routes.optimizeRoutes": "Optimize Routes",
    "routes.optimizingRoutes": "Optimizing Routes...",
    "routes.routeVisualization": "Route Visualization",
    "routes.optimizedRoutes": "Optimized Routes",
    "routes.routeStops": "Route Stops",
    "routes.alternatives": "Alternatives",
    "routes.option": "Option",
    "routes.km": "km",
    "routes.min": "min",
    "routes.saveRouteAssignments": "Save Route Assignments",
    "routes.exportRoute": "Export Route",
    "routes.exportForNavigation": "Export for Navigation",
    "routes.viewOnMap": "View on Map",
    "routes.currentRoute": "Current Route",
    "routes.alternativeRoute": "Alternative Route",
    "routes.gettingLocation": "Getting location...",
    "routes.locationError": "Unable to get location",
    "routes.locationSuccess": "Location updated successfully",

    "faq.q1": "How does the route optimization work?",
    "faq.a1": "Our AI-powered system uses advanced clustering algorithms to group employees by location, then generates multiple optimized routes considering distance, capacity, and efficiency.",

    "faq.q2": "Can I import existing employee data?",
    "faq.a2": "Yes! You can import employee data from Excel files and export your current data for backup or reporting purposes.",

    "faq.q3": "Is the system suitable for large organizations?",
    "faq.a3": "Absolutely. The system includes advanced filtering, pagination, and search capabilities to handle hundreds of employees and vehicles efficiently.",

    "faq.q4": "What languages are supported?",
    "faq.a4": "The system supports English, Spanish, German, French, and Turkish, making it suitable for global organizations.",
    "features.1.title": "Fleet Management",
    "features.1.description": "Track vehicles, capacity, maintenance, and availability in real-time",
    "features.1.feature1": "Vehicle tracking",
    "features.1.feature2": "Capacity management",
    "features.1.feature3": "Maintenance logs",
    "features.1.feature4": "Excel export/import",

    "features.2.title": "Employee Management",
    "features.2.description": "Centralized employee database with pickup locations and preferences",
    "features.2.feature1": "Contact management",
    "features.2.feature2": "GPS coordinates",
    "features.2.feature3": "Public transport info",
    "features.2.feature4": "Bulk operations",

    "features.3.title": "Route Optimization",
    "features.3.description": "AI-powered route planning with multiple alternatives and map visualization",
    "features.3.feature1": "Smart clustering",
    "features.3.feature2": "Multiple routes",
    "features.3.feature3": "Map visualization",
    "features.3.feature4": "Distance optimization",

    "features.4.title": "Advanced Filtering",
    "features.4.description": "Powerful search and filter capabilities across all data",
    "features.4.feature1": "Multi-field search",
    "features.4.feature2": "Custom filters",
    "features.4.feature3": "Saved searches",
    "features.4.feature4": "Quick actions",

    "features.5.title": "Analytics & Reports",
    "features.5.description": "Comprehensive reporting and data export capabilities",
    "features.5.feature1": "Usage analytics",
    "features.5.feature2": "Cost analysis",
    "features.5.feature3": "Excel reports",
    "features.5.feature4": "Performance metrics",

    "features.6.title": "Multi-Language",
    "features.6.description": "Global support with multiple language options",
    "features.6.feature1": "English",
    "features.6.feature2": "Spanish",
    "features.6.feature3": "German",
    "features.6.feature4": "French",
    "features.6.feature5": "Turkish",
    "howItWorks.1.title": "Fleet Management",
    "howItWorks.1.description": "Comprehensive vehicle management with detailed tracking",
    "howItWorks.1.step1": "Add vehicles with capacity, model, and specifications",
    "howItWorks.1.step2": "Track maintenance status and availability",
    "howItWorks.1.step3": "Monitor vehicle utilization and performance",
    "howItWorks.1.step4": "Export fleet data for reporting",

    "howItWorks.2.title": "Employee Management",
    "howItWorks.2.description": "Centralized employee information and pickup locations",
    "howItWorks.2.step1": "Register employees with contact information",
    "howItWorks.2.step2": "Set pickup locations with GPS coordinates",
    "howItWorks.2.step3": "Track nearest public transportation options",
    "howItWorks.2.step4": "Import/export employee data via Excel",

    "howItWorks.3.title": "Route Optimization",
    "howItWorks.3.description": "AI-powered intelligent route planning system",
    "howItWorks.3.step1": "Select employees and vehicles for optimization",
    "howItWorks.3.step2": "Generate multiple route alternatives",
    "howItWorks.3.step3": "Visualize routes on interactive maps",
    "howItWorks.3.step4": "Save and manage route assignments",

  },
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.cars": "Vehículos",
    "nav.employees": "Empleados",
    "nav.routeOptimization": "Optimización de Rutas",

    // Common
    "common.loading": "Cargando...",
    "common.search": "Buscar...",
    "common.filter": "Filtrar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.add": "Agregar",
    "common.update": "Actualizar",
    "common.export": "Exportar Excel",
    "common.import": "Importar Excel",
    "common.importing": "Importando...",
    "common.exporting": "Exportando...",
    "common.actions": "Acciones",
    "common.status": "Estado",
    "common.active": "Activo",
    "common.inactive": "Inactivo",
    "common.all": "Todos",
    "common.clear": "Limpiar",
    "common.previous": "Anterior",
    "common.next": "Siguiente",
    "common.page": "Página",
    "common.of": "de",
    "common.showing": "Mostrando",
    "common.results": "resultados",
    "common.for": "para",
    "common.required": "requerido",

    // Home Page
    "home.title": "Organizador de Autobuses",
    "home.subtitle":
      "Transforme su transporte de personal con optimización inteligente de rutas, gestión integral de flota y coordinación perfecta de empleados.",
    "home.manageFleet": "🚗 Gestionar Flota",
    "home.manageEmployees": "👥 Gestionar Empleados",
    "home.optimizeRoutes": "🗺️ Optimizar Rutas",
    "home.howItWorks": "Cómo Funciona",
    "home.howItWorksSubtitle": "Siga estos simples pasos para optimizar su sistema de transporte de personal",
    "home.powerfulFeatures": "Características Poderosas",
    "home.featuresSubtitle": "Todo lo que necesita para gestionar su sistema de transporte",
    "home.readyToStart": "¿Listo para Comenzar?",
    "home.startSubtitle": "Comience a optimizar su sistema de transporte de personal hoy",
    "home.faq": "Preguntas Frecuentes",

    // Cars Page
    "cars.title": "Gestión de Flota",
    "cars.subtitle": "Gestione su flota de vehículos con filtrado avanzado e integración Excel",
    "cars.addCar": "Agregar Vehículo",
    "cars.editCar": "Editar Vehículo",
    "cars.addNewCar": "Agregar Nuevo Vehículo",
    "cars.model": "Modelo",
    "cars.plateNumber": "Número de Placa",
    "cars.capacity": "Capacidad",
    "cars.color": "Color",
    "cars.year": "Año",
    "cars.notes": "Notas",
    "cars.people": "personas",
    "cars.selectColor": "Seleccionar color",
    "cars.modelPlaceholder": "ej., Mercedes Sprinter",
    "cars.platePlaceholder": "ej., ABC-123",
    "cars.capacityPlaceholder": "Número de pasajeros",
    "cars.notesPlaceholder": "Información adicional sobre el vehículo",
    "cars.modelRequired": "El modelo es requerido",
    "cars.plateRequired": "El número de placa es requerido",
    "cars.capacityRequired": "La capacidad debe estar entre 1 y 100",

    // Employees Page
    "employees.title": "Gestión de Empleados",
    "employees.subtitle": "Gestione la información de empleados con búsqueda avanzada e integración Excel",
    "employees.addEmployee": "Agregar Empleado",
    "employees.editEmployee": "Editar Empleado",
    "employees.addNewEmployee": "Agregar Nuevo Empleado",
    "employees.firstName": "Nombre",
    "employees.lastName": "Apellido",
    "employees.jobTitle": "Título del Trabajo",
    "employees.email": "Correo Electrónico",
    "employees.phoneNumber": "Número de Teléfono",
    "employees.homeAddress": "Dirección de Casa",
    "employees.dropOffPoint": "Punto de Bajada",
    "employees.dropOffLatitude": "Latitud de Bajada",
    "employees.dropOffLongitude": "Longitud de Bajada",
    "employees.nearestPublicTransport": "Transporte Público Más Cercano",
    "employees.personalInfo": "Información Personal",
    "employees.locationInfo": "Información de Ubicación",
    "employees.additionalInfo": "Información Adicional",
    "employees.firstNamePlaceholder": "Ingrese el nombre",
    "employees.lastNamePlaceholder": "Ingrese el apellido",
    "employees.emailPlaceholder": "empleado@empresa.com",

    // Route Optimization
    "routes.title": "Optimización de Rutas",
    "routes.subtitle": "Optimiza rutas de autobús con filtrado avanzado y visualización de mapas",
    "routes.workplaceLocation": "Ubicación del Trabajo",
    "routes.workplaceAddress": "Dirección del Trabajo",
    "routes.getCurrentLocation": "Obtener Ubicación Actual",
    "routes.selectCars": "Seleccionar Vehículos",
    "routes.selectEmployees": "Seleccionar Empleados",
    "routes.searchCars": "Buscar vehículos...",
    "routes.searchEmployees": "Buscar empleados...",
    "routes.filterByLocation": "Filtrar por ubicación...",
    "routes.minCapacity": "Capacidad mínima",
    "routes.seats": "asientos",
    "routes.optimizeRoutes": "Optimizar Rutas",
    "routes.optimizingRoutes": "Optimizando Rutas...",
    "routes.routeVisualization": "Visualización de Rutas",
    "routes.optimizedRoutes": "Rutas Optimizadas",
    "routes.routeStops": "Paradas de Ruta",
    "routes.alternatives": "Alternativas",
    "routes.option": "Opción",
    "routes.km": "km",
    "routes.min": "min",
    "routes.saveRouteAssignments": "Guardar Asignaciones de Ruta",
    "routes.exportRoute": "Exportar Ruta",
    "routes.exportForNavigation": "Exportar para Navegación",
    "routes.viewOnMap": "Ver en Mapa",
    "routes.currentRoute": "Ruta Actual",
    "routes.alternativeRoute": "Ruta Alternativa",
    "routes.gettingLocation": "Obteniendo ubicación...",
    "routes.locationError": "No se pudo obtener la ubicación",
    "routes.locationSuccess": "Ubicación actualizada exitosamente",

    "faq.q1": "¿Cómo funciona la optimización de rutas?",
    "faq.a1": "Nuestro sistema con inteligencia artificial utiliza algoritmos de agrupación avanzados para agrupar empleados por ubicación y generar múltiples rutas optimizadas considerando distancia, capacidad y eficiencia.",

    "faq.q2": "¿Puedo importar datos de empleados existentes?",
    "faq.a2": "¡Sí! Puede importar datos de empleados desde archivos Excel y exportar sus datos actuales para respaldos o informes.",

    "faq.q3": "¿El sistema es adecuado para grandes organizaciones?",
    "faq.a3": "Por supuesto. El sistema incluye filtrado avanzado, paginación y búsqueda para manejar cientos de empleados y vehículos eficientemente.",

    "faq.q4": "¿Qué idiomas son compatibles?",
    "faq.a4": "El sistema admite inglés, español, alemán, francés y turco, lo que lo hace adecuado para organizaciones globales.",
    "features.1.title": "Gestión de Flota",
    "features.1.description": "Controle vehículos, capacidad, mantenimiento y disponibilidad en tiempo real",
    "features.1.feature1": "Seguimiento de vehículos",
    "features.1.feature2": "Gestión de capacidad",
    "features.1.feature3": "Registros de mantenimiento",
    "features.1.feature4": "Importación/exportación Excel",

    "features.2.title": "Gestión de Empleados",
    "features.2.description": "Base de datos centralizada con ubicaciones de recogida",
    "features.2.feature1": "Gestión de contactos",
    "features.2.feature2": "Coordenadas GPS",
    "features.2.feature3": "Información de transporte público",
    "features.2.feature4": "Operaciones masivas",

    "features.3.title": "Optimización de Rutas",
    "features.3.description": "Planificación inteligente de rutas con múltiples alternativas y visualización de mapas",
    "features.3.feature1": "Agrupación inteligente",
    "features.3.feature2": "Rutas múltiples",
    "features.3.feature3": "Visualización de mapas",
    "features.3.feature4": "Optimización de distancias",

    "features.4.title": "Filtrado Avanzado",
    "features.4.description": "Potentes capacidades de búsqueda y filtrado en todos los datos",
    "features.4.feature1": "Búsqueda por múltiples campos",
    "features.4.feature2": "Filtros personalizados",
    "features.4.feature3": "Búsquedas guardadas",
    "features.4.feature4": "Acciones rápidas",

    "features.5.title": "Analítica e Informes",
    "features.5.description": "Informes completos y opciones de exportación de datos",
    "features.5.feature1": "Análisis de uso",
    "features.5.feature2": "Análisis de costes",
    "features.5.feature3": "Informes en Excel",
    "features.5.feature4": "Métricas de rendimiento",

    "features.6.title": "Multi-Idioma",
    "features.6.description": "Soporte global con múltiples opciones de idioma",
    "features.6.feature1": "Inglés",
    "features.6.feature2": "Español",
    "features.6.feature3": "Alemán",
    "features.6.feature4": "Francés",
    "features.6.feature5": "Turco",
    "howItWorks.1.title": "Gestión de Flota",
    "howItWorks.1.description": "Gestión integral de vehículos con seguimiento detallado",
    "howItWorks.1.step1": "Agrega vehículos con capacidad, modelo y especificaciones",
    "howItWorks.1.step2": "Supervisa el estado de mantenimiento y disponibilidad",
    "howItWorks.1.step3": "Controla el uso y rendimiento de los vehículos",
    "howItWorks.1.step4": "Exporta los datos de la flota para informes",

    "howItWorks.2.title": "Gestión de Empleados",
    "howItWorks.2.description": "Información centralizada de empleados y ubicaciones de recogida",
    "howItWorks.2.step1": "Registra empleados con su información de contacto",
    "howItWorks.2.step2": "Establece ubicaciones de recogida con coordenadas GPS",
    "howItWorks.2.step3": "Rastrea las opciones de transporte público más cercanas",
    "howItWorks.2.step4": "Importa/exporta datos de empleados desde Excel",

    "howItWorks.3.title": "Optimización de Rutas",
    "howItWorks.3.description": "Sistema inteligente de planificación de rutas basado en IA",
    "howItWorks.3.step1": "Selecciona empleados y vehículos para optimización",
    "howItWorks.3.step2": "Genera múltiples rutas alternativas",
    "howItWorks.3.step3": "Visualiza rutas en mapas interactivos",
    "howItWorks.3.step4": "Guarda y gestiona las asignaciones de ruta",
  },
  de: {
    // Navigation
    "nav.home": "Startseite",
    "nav.cars": "Fahrzeuge",
    "nav.employees": "Mitarbeiter",
    "nav.routeOptimization": "Routenoptimierung",

    // Common
    "common.loading": "Laden...",
    "common.search": "Suchen...",
    "common.filter": "Filter",
    "common.edit": "Bearbeiten",
    "common.delete": "Löschen",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.add": "Hinzufügen",
    "common.update": "Aktualisieren",
    "common.export": "Excel Exportieren",
    "common.import": "Excel Importieren",
    "common.importing": "Importiere...",
    "common.exporting": "Exportiere...",
    "common.actions": "Aktionen",
    "common.status": "Status",
    "common.active": "Aktiv",
    "common.inactive": "Inaktiv",
    "common.all": "Alle",
    "common.clear": "Löschen",
    "common.previous": "Vorherige",
    "common.next": "Nächste",
    "common.page": "Seite",
    "common.of": "von",
    "common.showing": "Zeige",
    "common.results": "Ergebnisse",
    "common.for": "für",
    "common.required": "erforderlich",

    // Home Page
    "home.title": "Bus Organizer",
    "home.subtitle":
      "Transformieren Sie Ihren Personentransport mit intelligenter Routenoptimierung, umfassendem Flottenmanagement und nahtloser Mitarbeiterkoordination.",
    "home.manageFleet": "🚗 Flotte Verwalten",
    "home.manageEmployees": "👥 Mitarbeiter Verwalten",
    "home.optimizeRoutes": "🗺️ Routen Optimieren",
    "home.howItWorks": "Wie Es Funktioniert",
    "home.howItWorksSubtitle": "Befolgen Sie diese einfachen Schritte, um Ihr Personentransportsystem zu optimieren",
    "home.powerfulFeatures": "Leistungsstarke Funktionen",
    "home.featuresSubtitle": "Alles was Sie brauchen, um Ihr Transportsystem zu verwalten",
    "home.readyToStart": "Bereit Anzufangen?",
    "home.startSubtitle": "Beginnen Sie noch heute mit der Optimierung Ihres Personentransportsystems",
    "home.faq": "Häufig Gestellte Fragen",

    // Cars Page
    "cars.title": "Flottenmanagement",
    "cars.subtitle": "Verwalten Sie Ihre Fahrzeugflotte mit erweiterten Filtern und Excel-Integration",
    "cars.addCar": "Fahrzeug Hinzufügen",
    "cars.editCar": "Fahrzeug Bearbeiten",
    "cars.addNewCar": "Neues Fahrzeug Hinzufügen",
    "cars.model": "Modell",
    "cars.plateNumber": "Kennzeichen",
    "cars.capacity": "Kapazität",
    "cars.color": "Farbe",
    "cars.year": "Jahr",
    "cars.notes": "Notizen",
    "cars.people": "Personen",
    "cars.selectColor": "Farbe auswählen",
    "cars.modelPlaceholder": "z.B. Mercedes Sprinter",
    "cars.platePlaceholder": "z.B. ABC-123",
    "cars.capacityPlaceholder": "Anzahl der Passagiere",
    "cars.notesPlaceholder": "Zusätzliche Informationen über das Fahrzeug",
    "cars.modelRequired": "Modell ist erforderlich",
    "cars.plateRequired": "Kennzeichen ist erforderlich",
    "cars.capacityRequired": "Kapazität muss zwischen 1 und 100 liegen",

    // Employees Page
    "employees.title": "Mitarbeiterverwaltung",
    "employees.subtitle": "Verwalten Sie Mitarbeiterinformationen mit erweiterter Suche und Excel-Integration",
    "employees.addEmployee": "Mitarbeiter Hinzufügen",
    "employees.editEmployee": "Mitarbeiter Bearbeiten",
    "employees.addNewEmployee": "Neuen Mitarbeiter Hinzufügen",
    "employees.firstName": "Vorname",
    "employees.lastName": "Nachname",
    "employees.jobTitle": "Berufsbezeichnung",
    "employees.email": "E-Mail",
    "employees.phoneNumber": "Telefonnummer",
    "employees.homeAddress": "Heimadresse",
    "employees.dropOffPoint": "Abholpunkt",
    "employees.dropOffLatitude": "Abhol-Breitengrad",
    "employees.dropOffLongitude": "Abhol-Längengrad",
    "employees.nearestPublicTransport": "Nächster Öffentlicher Verkehr",
    "employees.personalInfo": "Persönliche Informationen",
    "employees.locationInfo": "Standortinformationen",
    "employees.additionalInfo": "Zusätzliche Informationen",
    "employees.firstNamePlaceholder": "Vorname eingeben",
    "employees.lastNamePlaceholder": "Nachname eingeben",
    "employees.emailPlaceholder": "mitarbeiter@firma.com",

    // Route Optimization
    "routes.title": "Routenoptimierung",
    "routes.subtitle": "Optimieren Sie Busrouten mit erweiterten Filtern und Kartenvisualisierung",
    "routes.workplaceLocation": "Arbeitsplatz-Standort",
    "routes.workplaceAddress": "Arbeitsplatz-Adresse",
    "routes.getCurrentLocation": "Aktuelle Position abrufen",
    "routes.selectCars": "Fahrzeuge auswählen",
    "routes.selectEmployees": "Mitarbeiter auswählen",
    "routes.searchCars": "Fahrzeuge suchen...",
    "routes.searchEmployees": "Mitarbeiter suchen...",
    "routes.filterByLocation": "Nach Standort filtern...",
    "routes.minCapacity": "Mindestkapazität",
    "routes.seats": "Sitze",
    "routes.optimizeRoutes": "Routen optimieren",
    "routes.optimizingRoutes": "Routen werden optimiert...",
    "routes.routeVisualization": "Routenvisualisierung",
    "routes.optimizedRoutes": "Optimierte Routen",
    "routes.routeStops": "Routenstopps",
    "routes.alternatives": "Alternativen",
    "routes.option": "Option",
    "routes.km": "km",
    "routes.min": "Min",
    "routes.saveRouteAssignments": "Routenzuweisungen speichern",
    "routes.exportRoute": "Route exportieren",
    "routes.exportForNavigation": "Für Navigation exportieren",
    "routes.viewOnMap": "Auf Karte anzeigen",
    "routes.currentRoute": "Aktuelle Route",
    "routes.alternativeRoute": "Alternative Route",
    "routes.gettingLocation": "Position wird abgerufen...",
    "routes.locationError": "Position konnte nicht abgerufen werden",
    "routes.locationSuccess": "Position erfolgreich aktualisiert",

    "faq.q1": "Wie funktioniert die Routenoptimierung?",
    "faq.a1": "Unser KI-gestütztes System verwendet fortschrittliche Clustering-Algorithmen, um Mitarbeiter nach Standort zu gruppieren und mehrere optimierte Routen unter Berücksichtigung von Entfernung, Kapazität und Effizienz zu erstellen.",

    "faq.q2": "Kann ich vorhandene Mitarbeiterdaten importieren?",
    "faq.a2": "Ja! Sie können Mitarbeiterdaten aus Excel-Dateien importieren und Ihre aktuellen Daten zur Sicherung oder Berichterstattung exportieren.",

    "faq.q3": "Ist das System für große Organisationen geeignet?",
    "faq.a3": "Auf jeden Fall. Das System enthält erweitertes Filtern, Paginierung und Suchfunktionen, um Hunderte von Mitarbeitern und Fahrzeugen effizient zu verwalten.",

    "faq.q4": "Welche Sprachen werden unterstützt?",
    "faq.a4": "Das System unterstützt Englisch, Spanisch, Deutsch, Französisch und Türkisch und ist somit ideal für globale Organisationen.",
    "features.1.title": "Flottenmanagement",
    "features.1.description": "Verfolgen Sie Fahrzeuge, Kapazitäten, Wartung und Verfügbarkeit in Echtzeit",
    "features.1.feature1": "Fahrzeugverfolgung",
    "features.1.feature2": "Kapazitätsverwaltung",
    "features.1.feature3": "Wartungsprotokolle",
    "features.1.feature4": "Excel-Import/-Export",

    "features.2.title": "Mitarbeiterverwaltung",
    "features.2.description": "Zentrale Mitarbeiterdatenbank mit Abholorten und Präferenzen",
    "features.2.feature1": "Kontaktverwaltung",
    "features.2.feature2": "GPS-Koordinaten",
    "features.2.feature3": "ÖPNV-Informationen",
    "features.2.feature4": "Massenoperationen",

    "features.3.title": "Routenoptimierung",
    "features.3.description": "KI-gestützte Routenplanung mit Alternativen und Kartenvisualisierung",
    "features.3.feature1": "Intelligentes Clustering",
    "features.3.feature2": "Mehrere Routen",
    "features.3.feature3": "Kartenvisualisierung",
    "features.3.feature4": "Entfernungsoptimierung",

    "features.4.title": "Erweiterte Filterung",
    "features.4.description": "Leistungsstarke Such- und Filterfunktionen für alle Daten",
    "features.4.feature1": "Mehrfeldsuche",
    "features.4.feature2": "Benutzerdefinierte Filter",
    "features.4.feature3": "Gespeicherte Suchen",
    "features.4.feature4": "Schnellaktionen",

    "features.5.title": "Analysen & Berichte",
    "features.5.description": "Umfassende Berichte und Datenexport-Funktionen",
    "features.5.feature1": "Nutzungsanalysen",
    "features.5.feature2": "Kostenanalyse",
    "features.5.feature3": "Excel-Berichte",
    "features.5.feature4": "Leistungskennzahlen",

    "features.6.title": "Mehrsprachigkeit",
    "features.6.description": "Globale Unterstützung mit mehreren Sprachoptionen",
    "features.6.feature1": "Englisch",
    "features.6.feature2": "Spanisch",
    "features.6.feature3": "Deutsch",
    "features.6.feature4": "Französisch",
    "features.6.feature5": "Türkisch",
    "howItWorks.1.title": "Flottenmanagement",
    "howItWorks.1.description": "Umfassende Fahrzeugverwaltung mit detaillierter Nachverfolgung",
    "howItWorks.1.step1": "Fahrzeuge mit Kapazität, Modell und Spezifikationen hinzufügen",
    "howItWorks.1.step2": "Wartungsstatus und Verfügbarkeit verfolgen",
    "howItWorks.1.step3": "Fahrzeugnutzung und -leistung überwachen",
    "howItWorks.1.step4": "Flottendaten für Berichte exportieren",

    "howItWorks.2.title": "Mitarbeiterverwaltung",
    "howItWorks.2.description": "Zentralisierte Mitarbeiterdaten mit Abholorten",
    "howItWorks.2.step1": "Mitarbeiter mit Kontaktinformationen registrieren",
    "howItWorks.2.step2": "Abholorte mit GPS-Koordinaten festlegen",
    "howItWorks.2.step3": "Nächstgelegene öffentliche Verkehrsmittel verfolgen",
    "howItWorks.2.step4": "Mitarbeiterdaten über Excel importieren/exportieren",

    "howItWorks.3.title": "Routenoptimierung",
    "howItWorks.3.description": "KI-gestütztes intelligentes Routenplanungssystem",
    "howItWorks.3.step1": "Mitarbeiter und Fahrzeuge zur Optimierung auswählen",
    "howItWorks.3.step2": "Mehrere Routenalternativen generieren",
    "howItWorks.3.step3": "Routen auf interaktiven Karten visualisieren",
    "howItWorks.3.step4": "Routenzuweisungen speichern und verwalten",
  },
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.cars": "Véhicules",
    "nav.employees": "Employés",
    "nav.routeOptimization": "Optimisation des Itinéraires",

    // Common
    "common.loading": "Chargement...",
    "common.search": "Rechercher...",
    "common.filter": "Filtrer",
    "common.edit": "Modifier",
    "common.delete": "Supprimer",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.add": "Ajouter",
    "common.update": "Mettre à jour",
    "common.export": "Exporter Excel",
    "common.import": "Importer Excel",
    "common.importing": "Importation...",
    "common.exporting": "Exportation...",
    "common.actions": "Actions",
    "common.status": "Statut",
    "common.active": "Actif",
    "common.inactive": "Inactif",
    "common.all": "Tous",
    "common.clear": "Effacer",
    "common.previous": "Précédent",
    "common.next": "Suivant",
    "common.page": "Page",
    "common.of": "de",
    "common.showing": "Affichage",
    "common.results": "résultats",
    "common.for": "pour",
    "common.required": "requis",

    // Home Page
    "home.title": "Organisateur de Bus",
    "home.subtitle":
      "Transformez votre transport de personnel avec une optimisation intelligente des itinéraires, une gestion complète de flotte et une coordination transparente des employés.",
    "home.manageFleet": "🚗 Gérer la Flotte",
    "home.manageEmployees": "👥 Gérer les Employés",
    "home.optimizeRoutes": "🗺️ Optimiser les Itinéraires",
    "home.howItWorks": "Comment Ça Marche",
    "home.howItWorksSubtitle": "Suivez ces étapes simples pour optimiser votre système de transport de personnel",
    "home.powerfulFeatures": "Fonctionnalités Puissantes",
    "home.featuresSubtitle": "Tout ce dont vous avez besoin pour gérer votre système de transport",
    "home.readyToStart": "Prêt à Commencer?",
    "home.startSubtitle": "Commencez à optimiser votre système de transport de personnel aujourd'hui",
    "home.faq": "Questions Fréquemment Posées",

    // Cars Page
    "cars.title": "Gestion de Flotte",
    "cars.subtitle": "Gérez votre flotte de véhicules avec un filtrage avancé et une intégration Excel",
    "cars.addCar": "Ajouter Véhicule",
    "cars.editCar": "Modifier Véhicule",
    "cars.addNewCar": "Ajouter Nouveau Véhicule",
    "cars.model": "Modèle",
    "cars.plateNumber": "Numéro de Plaque",
    "cars.capacity": "Capacité",
    "cars.color": "Couleur",
    "cars.year": "Année",
    "cars.notes": "Notes",
    "cars.people": "personnes",
    "cars.selectColor": "Sélectionner couleur",
    "cars.modelPlaceholder": "ex. Mercedes Sprinter",
    "cars.platePlaceholder": "ex. ABC-123",
    "cars.capacityPlaceholder": "Nombre de passagers",
    "cars.notesPlaceholder": "Informations supplémentaires sur le véhicule",
    "cars.modelRequired": "Le modèle est requis",
    "cars.plateRequired": "Le numéro de plaque est requis",
    "cars.capacityRequired": "La capacité doit être entre 1 et 100",

    // Employees Page
    "employees.title": "Gestion des Employés",
    "employees.subtitle": "Gérez les informations des employés avec une recherche avancée et une intégration Excel",
    "employees.addEmployee": "Ajouter Employé",
    "employees.editEmployee": "Modifier Employé",
    "employees.addNewEmployee": "Ajouter Nouvel Employé",
    "employees.firstName": "Prénom",
    "employees.lastName": "Nom de Famille",
    "employees.jobTitle": "Titre du Poste",
    "employees.email": "E-mail",
    "employees.phoneNumber": "Numéro de Téléphone",
    "employees.homeAddress": "Adresse Domicile",
    "employees.dropOffPoint": "Point de Dépose",
    "employees.dropOffLatitude": "Latitude de Dépose",
    "employees.dropOffLongitude": "Longitude de Dépose",
    "employees.nearestPublicTransport": "Transport Public le Plus Proche",
    "employees.personalInfo": "Informations Personnelles",
    "employees.locationInfo": "Informations de Localisation",
    "employees.additionalInfo": "Informations Supplémentaires",
    "employees.firstNamePlaceholder": "Entrez le prénom",
    "employees.lastNamePlaceholder": "Entrez le nom de famille",
    "employees.emailPlaceholder": "employe@entreprise.com",

    // Route Optimization
    "routes.title": "Optimisation des Itinéraires",
    "routes.subtitle": "Optimisez les itinéraires de bus avec filtrage avancé et visualisation cartographique",
    "routes.workplaceLocation": "Emplacement du Lieu de Travail",
    "routes.workplaceAddress": "Adresse du Lieu de Travail",
    "routes.getCurrentLocation": "Obtenir la Position Actuelle",
    "routes.selectCars": "Sélectionner les Véhicules",
    "routes.selectEmployees": "Sélectionner les Employés",
    "routes.searchCars": "Rechercher des véhicules...",
    "routes.searchEmployees": "Rechercher des employés...",
    "routes.filterByLocation": "Filtrer par emplacement...",
    "routes.minCapacity": "Capacité minimale",
    "routes.seats": "sièges",
    "routes.optimizeRoutes": "Optimiser les Itinéraires",
    "routes.optimizingRoutes": "Optimisation des Itinéraires...",
    "routes.routeVisualization": "Visualisation des Itinéraires",
    "routes.optimizedRoutes": "Itinéraires Optimisés",
    "routes.routeStops": "Arrêts d'Itinéraire",
    "routes.alternatives": "Alternatives",
    "routes.option": "Option",
    "routes.km": "km",
    "routes.min": "min",
    "routes.saveRouteAssignments": "Enregistrer les Affectations d'Itinéraire",
    "routes.exportRoute": "Exporter l'Itinéraire",
    "routes.exportForNavigation": "Exporter pour la Navigation",
    "routes.viewOnMap": "Voir sur la Carte",
    "routes.currentRoute": "Itinéraire Actuel",
    "routes.alternativeRoute": "Itinéraire Alternatif",
    "routes.gettingLocation": "Obtention de la position...",
    "routes.locationError": "Impossible d'obtenir la position",
    "routes.locationSuccess": "Position mise à jour avec succès",

    "faq.q1": "Comment fonctionne l’optimisation des itinéraires ?",
    "faq.a1": "Notre système basé sur l’IA utilise des algorithmes de regroupement avancés pour regrouper les employés par localisation, puis génère plusieurs itinéraires optimisés en tenant compte de la distance, de la capacité et de l’efficacité.",

    "faq.q2": "Puis-je importer des données d’employés existantes ?",
    "faq.a2": "Oui ! Vous pouvez importer des données depuis des fichiers Excel et exporter vos données actuelles pour les sauvegardes ou les rapports.",

    "faq.q3": "Le système convient-il aux grandes entreprises ?",
    "faq.a3": "Absolument. Le système comprend un filtrage avancé, une pagination et une recherche puissante pour gérer efficacement des centaines d’employés et de véhicules.",

    "faq.q4": "Quelles langues sont prises en charge ?",
    "faq.a4": "Le système prend en charge l’anglais, l’espagnol, l’allemand, le français et le turc, ce qui le rend adapté aux organisations internationales.",

    "features.1.title": "Gestion de Flotte",
    "features.1.description": "Suivez les véhicules, la capacité, l’entretien et la disponibilité en temps réel",
    "features.1.feature1": "Suivi des véhicules",
    "features.1.feature2": "Gestion de la capacité",
    "features.1.feature3": "Journaux de maintenance",
    "features.1.feature4": "Import/export Excel",

    "features.2.title": "Gestion des Employés",
    "features.2.description": "Base de données centralisée avec lieux de ramassage et préférences",
    "features.2.feature1": "Gestion des contacts",
    "features.2.feature2": "Coordonnées GPS",
    "features.2.feature3": "Infos transport public",
    "features.2.feature4": "Opérations en masse",

    "features.3.title": "Optimisation des Itinéraires",
    "features.3.description": "Planification intelligente avec alternatives multiples et cartes interactives",
    "features.3.feature1": "Regroupement intelligent",
    "features.3.feature2": "Itinéraires multiples",
    "features.3.feature3": "Visualisation de cartes",
    "features.3.feature4": "Optimisation des distances",

    "features.4.title": "Filtrage Avancé",
    "features.4.description": "Fonctionnalités de recherche et filtrage puissantes",
    "features.4.feature1": "Recherche multicritère",
    "features.4.feature2": "Filtres personnalisés",
    "features.4.feature3": "Recherches enregistrées",
    "features.4.feature4": "Actions rapides",

    "features.5.title": "Analyses & Rapports",
    "features.5.description": "Rapports complets et exportation des données",
    "features.5.feature1": "Analyse d’utilisation",
    "features.5.feature2": "Analyse des coûts",
    "features.5.feature3": "Rapports Excel",
    "features.5.feature4": "Indicateurs de performance",

    "features.6.title": "Multi-langue",
    "features.6.description": "Support mondial avec plusieurs langues",
    "features.6.feature1": "Anglais",
    "features.6.feature2": "Espagnol",
    "features.6.feature3": "Allemand",
    "features.6.feature4": "Français",
    "features.6.feature5": "Turc",
    "howItWorks.1.title": "Gestion de Flotte",
    "howItWorks.1.description": "Gestion complète des véhicules avec suivi détaillé",
    "howItWorks.1.step1": "Ajoutez des véhicules avec capacité, modèle et spécifications",
    "howItWorks.1.step2": "Suivez l’état de maintenance et la disponibilité",
    "howItWorks.1.step3": "Surveillez l’utilisation et la performance des véhicules",
    "howItWorks.1.step4": "Exportez les données de flotte pour les rapports",

    "howItWorks.2.title": "Gestion des Employés",
    "howItWorks.2.description": "Informations centralisées sur les employés et lieux de prise en charge",
    "howItWorks.2.step1": "Enregistrez les employés avec leurs coordonnées",
    "howItWorks.2.step2": "Définissez les points de prise en charge avec des coordonnées GPS",
    "howItWorks.2.step3": "Suivez les options de transport public les plus proches",
    "howItWorks.2.step4": "Importez/exportez les données d’employés via Excel",

    "howItWorks.3.title": "Optimisation des Itinéraires",
    "howItWorks.3.description": "Système intelligent de planification d’itinéraires basé sur l’IA",
    "howItWorks.3.step1": "Sélectionnez les employés et véhicules à optimiser",
    "howItWorks.3.step2": "Générez plusieurs itinéraires alternatifs",
    "howItWorks.3.step3": "Visualisez les itinéraires sur des cartes interactives",
    "howItWorks.3.step4": "Enregistrez et gérez les affectations de route",

  },
  tr: {
    // Navigation
    "nav.home": "Ana Sayfa",
    "nav.cars": "Araçlar",
    "nav.employees": "Çalışanlar",
    "nav.routeOptimization": "Rota Optimizasyonu",

    // Common
    "common.loading": "Yükleniyor...",
    "common.search": "Ara...",
    "common.filter": "Filtrele",
    "common.edit": "Düzenle",
    "common.delete": "Sil",
    "common.save": "Kaydet",
    "common.cancel": "İptal",
    "common.add": "Ekle",
    "common.update": "Güncelle",
    "common.export": "Excel Dışa Aktar",
    "common.import": "Excel İçe Aktar",
    "common.importing": "İçe Aktarılıyor...",
    "common.exporting": "Dışa Aktarılıyor...",
    "common.actions": "İşlemler",
    "common.status": "Durum",
    "common.active": "Aktif",
    "common.inactive": "Pasif",
    "common.all": "Tümü",
    "common.clear": "Temizle",
    "common.previous": "Önceki",
    "common.next": "Sonraki",
    "common.page": "Sayfa",
    "common.of": "/",
    "common.showing": "Gösteriliyor",
    "common.results": "sonuç",
    "common.for": "için",
    "common.required": "gerekli",

    // Home Page
    "home.title": "Otobüs Organizatörü",
    "home.subtitle":
      "Akıllı rota optimizasyonu, kapsamlı filo yönetimi ve sorunsuz çalışan koordinasyonu ile personel taşımacılığınızı dönüştürün.",
    "home.manageFleet": "🚗 Filoyu Yönet",
    "home.manageEmployees": "👥 Çalışanları Yönet",
    "home.optimizeRoutes": "🗺️ Rotaları Optimize Et",
    "home.howItWorks": "Nasıl Çalışır",
    "home.howItWorksSubtitle": "Personel taşıma sisteminizi optimize etmek için bu basit adımları izleyin",
    "home.powerfulFeatures": "Öne Çıkan Özellikler",
    "home.featuresSubtitle": "Taşıma sisteminizi yönetmek için ihtiyacınız olan her şey",
    "home.readyToStart": "Başlamaya Hazır mısınız?",
    "home.startSubtitle": "Personel taşıma sisteminizi bugün optimize etmeye başlayın",
    "home.faq": "Sık Sorulan Sorular",

    // Cars Page
    "cars.title": "Filo Yönetimi",
    "cars.subtitle": "Gelişmiş filtreleme ve Excel entegrasyonu ile araç filonuzu yönetin",
    "cars.addCar": "Araç Ekle",
    "cars.editCar": "Araç Düzenle",
    "cars.addNewCar": "Yeni Araç Ekle",
    "cars.model": "Model",
    "cars.plateNumber": "Plaka Numarası",
    "cars.capacity": "Kapasite",
    "cars.color": "Renk",
    "cars.year": "Yıl",
    "cars.notes": "Notlar",
    "cars.people": "kişi",
    "cars.selectColor": "Renk seçin",
    "cars.modelPlaceholder": "örn. Mercedes Sprinter",
    "cars.platePlaceholder": "örn. ABC-123",
    "cars.capacityPlaceholder": "Yolcu sayısı",
    "cars.notesPlaceholder": "Araç hakkında ek bilgiler",
    "cars.modelRequired": "Model gereklidir",
    "cars.plateRequired": "Plaka numarası gereklidir",
    "cars.capacityRequired": "Kapasite 1 ile 100 arasında olmalıdır",

    // Employees Page
    "employees.title": "Çalışan Yönetimi",
    "employees.subtitle": "Gelişmiş arama ve Excel entegrasyonu ile çalışan bilgilerini yönetin",
    "employees.addEmployee": "Çalışan Ekle",
    "employees.editEmployee": "Çalışan Düzenle",
    "employees.addNewEmployee": "Yeni Çalışan Ekle",
    "employees.firstName": "Ad",
    "employees.lastName": "Soyad",
    "employees.jobTitle": "İş Unvanı",
    "employees.email": "E-posta",
    "employees.phoneNumber": "Telefon Numarası",
    "employees.homeAddress": "Ev Adresi",
    "employees.dropOffPoint": "İniş Noktası",
    "employees.dropOffLatitude": "İniş Enlem",
    "employees.dropOffLongitude": "İniş Boylam",
    "employees.nearestPublicTransport": "En Yakın Toplu Taşıma",
    "employees.personalInfo": "Kişisel Bilgiler",
    "employees.locationInfo": "Konum Bilgileri",
    "employees.additionalInfo": "Ek Bilgiler",
    "employees.firstNamePlaceholder": "Adı girin",
    "employees.lastNamePlaceholder": "Soyadı girin",
    "employees.emailPlaceholder": "calisan@sirket.com",

    // Route Optimization
    "routes.title": "Rota Optimizasyonu",
    "routes.subtitle": "Gelişmiş filtreleme ve harita görselleştirmesi ile otobüs rotalarını optimize edin",
    "routes.workplaceLocation": "İşyeri Konumu",
    "routes.workplaceAddress": "İşyeri Adresi",
    "routes.getCurrentLocation": "Konumu Kullan",
    "routes.selectCars": "Araç Seç",
    "routes.selectEmployees": "Çalışan Seç",
    "routes.optimizeRoutes": "Rotaları Optimize Et",
    "routes.optimizingRoutes": "Rotalar Optimize Ediliyor...",
    "routes.routeVisualization": "Rota Görselleştirmesi",
    "routes.optimizedRoutes": "Optimize Edilmiş Rotalar",
    "routes.routeStops": "Rota Durakları",
    "routes.alternatives": "Alternatifler",
    "routes.saveRouteAssignments": "Rota Atamalarını Kaydet",
    "routes.searchCars": "Araç ara...",
    "routes.searchEmployees": "Çalışan ara...",
    "routes.filterByLocation": "Konuma göre filtrele...",
    "routes.minCapacity": "Minimum kapasite",
    "routes.seats": "koltuk",
    "routes.km": "km",
    "routes.min": "dk",
    "routes.option": "Seçenek",
    "routes.exportRoute": "Rotayı Dışa Aktar",
    "routes.exportForNavigation": "Navigasyon için Dışa Aktar",
    "routes.viewOnMap": "Haritada Görüntüle",
    "routes.currentRoute": "Mevcut Rota",
    "routes.alternativeRoute": "Alternatif Rota",
    "routes.gettingLocation": "Konum alınıyor...",
    "routes.locationError": "Konum alınamadı",
    "routes.locationSuccess": "Konum başarıyla güncellendi",
    "faq.q1": "Rota optimizasyonu nasıl çalışır?",
    "faq.a1": "Yapay zekâ destekli sistemimiz, çalışanları konuma göre gruplamak için gelişmiş kümeleme algoritmaları kullanır ve mesafe, kapasite ve verimliliği dikkate alarak birden fazla optimize edilmiş rota oluşturur.",

    "faq.q2": "Mevcut çalışan verilerini içe aktarabilir miyim?",
    "faq.a2": "Evet! Excel dosyalarından çalışan verilerini içe aktarabilir ve mevcut verilerinizi yedekleme veya raporlama amacıyla dışa aktarabilirsiniz.",

    "faq.q3": "Sistem büyük organizasyonlar için uygun mu?",
    "faq.a3": "Kesinlikle. Sistem, yüzlerce çalışan ve aracı verimli bir şekilde yönetmek için gelişmiş filtreleme, sayfalama ve arama yetenekleri sunar.",

    "faq.q4": "Hangi diller destekleniyor?",
    "faq.a4": "Sistem; İngilizce, İspanyolca, Almanca, Fransızca ve Türkçe dillerini destekleyerek küresel organizasyonlara uygundur.",

    "features.1.title": "Filo Yönetimi",
    "features.1.description": "Araçları, kapasiteyi, bakımı ve kullanılabilirliği gerçek zamanlı izleyin",
    "features.1.feature1": "Araç takibi",
    "features.1.feature2": "Kapasite yönetimi",
    "features.1.feature3": "Bakım kayıtları",
    "features.1.feature4": "Excel içe/dışa aktarım",

    "features.2.title": "Çalışan Yönetimi",
    "features.2.description": "Toplama noktalarıyla merkezi çalışan veritabanı",
    "features.2.feature1": "İletişim yönetimi",
    "features.2.feature2": "GPS koordinatları",
    "features.2.feature3": "Toplu taşıma bilgisi",
    "features.2.feature4": "Toplu işlemler",

    "features.3.title": "Rota Optimizasyonu",
    "features.3.description": "Alternatifli yapay zeka destekli rota planlaması ve harita görselleştirme",
    "features.3.feature1": "Akıllı gruplama",
    "features.3.feature2": "Çoklu rota seçeneği",
    "features.3.feature3": "Harita görselleştirmesi",
    "features.3.feature4": "Mesafe optimizasyonu",

    "features.4.title": "Gelişmiş Filtreleme",
    "features.4.description": "Tüm veriler üzerinde güçlü arama ve filtreleme özellikleri",
    "features.4.feature1": "Çok alanlı arama",
    "features.4.feature2": "Özel filtreler",
    "features.4.feature3": "Kayıtlı aramalar",
    "features.4.feature4": "Hızlı işlemler",

    "features.5.title": "Analiz ve Raporlama",
    "features.5.description": "Kapsamlı raporlama ve veri dışa aktarım yetenekleri",
    "features.5.feature1": "Kullanım analizi",
    "features.5.feature2": "Maliyet analizi",
    "features.5.feature3": "Excel raporları",
    "features.5.feature4": "Performans metrikleri",

    "features.6.title": "Çok Dilli Destek",
    "features.6.description": "Birden fazla dil seçeneğiyle küresel destek",
    "features.6.feature1": "İngilizce",
    "features.6.feature2": "İspanyolca",
    "features.6.feature3": "Almanca",
    "features.6.feature4": "Fransızca",
    "features.6.feature5": "Türkçe",

    "howItWorks.1.title": "Filo Yönetimi",
    "howItWorks.1.description": "Detaylı izleme ile kapsamlı araç yönetimi",
    "howItWorks.1.step1": "Kapasite, model ve özelliklerle araç ekleyin",
    "howItWorks.1.step2": "Bakım durumu ve uygunluğu takip edin",
    "howItWorks.1.step3": "Araç kullanımını ve performansını izleyin",
    "howItWorks.1.step4": "Raporlama için filo verilerini dışa aktarın",

    "howItWorks.2.title": "Çalışan Yönetimi",
    "howItWorks.2.description": "Merkezi çalışan bilgisi ve toplama noktaları",
    "howItWorks.2.step1": "İletişim bilgileriyle çalışanları kaydedin",
    "howItWorks.2.step2": "GPS koordinatları ile toplama noktaları belirleyin",
    "howItWorks.2.step3": "En yakın toplu taşıma seçeneklerini takip edin",
    "howItWorks.2.step4": "Excel üzerinden çalışan verilerini içe/dışa aktarın",

    "howItWorks.3.title": "Rota Optimizasyonu",
    "howItWorks.3.description": "Yapay zekâ destekli akıllı rota planlama sistemi",
    "howItWorks.3.step1": "Optimizasyon için çalışanları ve araçları seçin",
    "howItWorks.3.step2": "Birden fazla rota alternatifi oluşturun",
    "howItWorks.3.step3": "Rotaları etkileşimli haritalarda görselleştirin",
    "howItWorks.3.step4": "Rota atamalarını kaydedin ve yönetin",

  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") || "en"
    setLanguage(savedLanguage)
  }, [])

  const changeLanguage = (lang: string) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    const langTranslations = translations[language as keyof typeof translations] as Record<string, string>
    return langTranslations[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>{children}</LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
